### ISSUE TITLE
Bug in the API

### ISSUE THREAD

**Issue by mathanamathav** [mathanamathav/bunker-api#10]
error message :

```
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
while trying to return_attendance function in the line session.get(url) throws this error.

**Comment by mathanamathav** [comment]
fixes shows there is nothing we can do about it -> https://github.com/RallyTools/RallyRestToolkitForPython/issues/179 

tried this but didn't fix it -> https://stackoverflow.com/questions/27333671/how-to-solve-the-10054-error

**Comment by mathanamathav** [comment]
@Hafiz408 i think it's started to work fine ig now the student's attendance is on progress once they update it will work again ig

**Comment by Hafiz408** [comment]
@mathanamathav  Great da
